/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package srbn.GUI;

import srbn.DataStructures.Graph.AdyMatrix;
import srbn.DataStructures.Graph.MatrixCell;
import srbn.DataStructures.Graph.NodeG;
import srbn.DataStructures.Lists.CellList.OrderedCellList;
import srbn.DataStructures.Lists.GenericList.GenericOrderedList;
import srbn.DataStructures.Tree.TreeB;
import srbn.FilesManagement.FileManager;

import javax.swing.*;
import java.io.File;

/**
 * @author ADMIN
 */
public class TravelMapGT extends javax.swing.JFrame {

    /**
     * Creates new form TravelMapGT
     */
    private AdyMatrix adyMatrix;
    private GUIController guiController = new GUIController();
    private TreeB<OrderedCellList> treeB = new TreeB<>(5);
    private GenericOrderedList<OrderedCellList> actualPaths = new GenericOrderedList<>();
    private int orderedBy = 0;

    public TravelMapGT() {
        initComponents();
        setLocationRelativeTo(null);
        adyMatrix = new AdyMatrix();
        guiController.setClock(this, hourLabel);
        navigatePanel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        infoPanel = new javax.swing.JPanel();
        hourLabel = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        srcComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        destComboBox2 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        travelButton = new javax.swing.JButton();
        fullMapViewButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        isWalkButton = new javax.swing.JToggleButton();
        routeInfoPanel = new javax.swing.JScrollPane();
        infoRouteLabel = new javax.swing.JTextArea();
        pathsPanel = new javax.swing.JPanel();
        pathsScrollPane = new javax.swing.JScrollPane();
        pathsScroll = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        orderByButton = new javax.swing.JButton();
        orderComboBox = new javax.swing.JComboBox<>();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        navigatePanel = new javax.swing.JPanel();
        destComboBox3 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        ubicationLabel = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        navigateButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        logTextArea = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        mapPanel = new javax.swing.JScrollPane();
        toGraphLabel = new javax.swing.JLabel();
        routePanel = new javax.swing.JScrollPane();
        routeMapLabel = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        fileJMenu = new javax.swing.JMenu();
        addLocation = new javax.swing.JMenuItem();
        addTrafficInfo = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        saveMap = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        graphTreeOption = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        pauseClock = new javax.swing.JMenuItem();
        editHour = new javax.swing.JMenuItem();
        resetClock = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 102));

        infoPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        infoPanel.setForeground(new java.awt.Color(102, 102, 102));

        hourLabel.setText("jLabel1");

        jLabel1.setText("Hora:");

        srcComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Origen"}));

        jLabel2.setText("Origen ");

        destComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Destino"}));

        jLabel3.setText("Destino");

        travelButton.setText("Calcular Viaje");
        travelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                travelButtonActionPerformed(evt);
            }
        });

        fullMapViewButton.setText("Ver mapa");
        fullMapViewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fullMapViewButtonActionPerformed(evt);
            }
        });

        jLabel4.setText("Modo:");

        isWalkButton.setText("Automovil");
        isWalkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isWalkButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout infoPanelLayout = new javax.swing.GroupLayout(infoPanel);
        infoPanel.setLayout(infoPanelLayout);
        infoPanelLayout.setHorizontalGroup(
            infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(travelButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(destComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator2)
                    .addGroup(infoPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hourLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(srcComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(infoPanelLayout.createSequentialGroup()
                        .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(infoPanelLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(infoPanelLayout.createSequentialGroup()
                                .addComponent(fullMapViewButton, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(isWalkButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        infoPanelLayout.setVerticalGroup(
            infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoPanelLayout.createSequentialGroup()
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hourLabel)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(srcComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(5, 5, 5)
                .addComponent(destComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(travelButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(isWalkButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(fullMapViewButton)
                        .addComponent(jLabel4)))
                .addGap(6, 6, 6))
        );

        infoRouteLabel.setColumns(20);
        infoRouteLabel.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        infoRouteLabel.setLineWrap(true);
        infoRouteLabel.setRows(5);
        infoRouteLabel.setWrapStyleWord(true);
        infoRouteLabel.setAutoscrolls(false);
        infoRouteLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        infoRouteLabel.setFocusable(false);
        routeInfoPanel.setViewportView(infoRouteLabel);

        pathsPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        pathsScrollPane.setBorder(null);
        pathsScrollPane.setToolTipText("");

        pathsScroll.setLayout(new java.awt.GridLayout(1, 1));
        pathsScrollPane.setViewportView(pathsScroll);

        jLabel6.setText("Caminos encontrados:");

        orderByButton.setText("Ordenar");
        orderByButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderByButtonActionPerformed(evt);
            }
        });

        orderComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Distancia", "Desgaste", "Consumo", "Tiempo" }));

        javax.swing.GroupLayout pathsPanelLayout = new javax.swing.GroupLayout(pathsPanel);
        pathsPanel.setLayout(pathsPanelLayout);
        pathsPanelLayout.setHorizontalGroup(
            pathsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pathsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pathsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pathsScrollPane)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pathsPanelLayout.createSequentialGroup()
                        .addGroup(pathsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pathsPanelLayout.createSequentialGroup()
                                .addComponent(orderByButton, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(orderComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pathsPanelLayout.setVerticalGroup(
            pathsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pathsPanelLayout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addGroup(pathsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(orderByButton)
                    .addComponent(orderComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pathsScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel7.setText("Ruta:");

        navigatePanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        destComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Destino"}));

        jLabel5.setText("Ubicacion:");

        ubicationLabel.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        ubicationLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ubicationLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel8.setText("Siguiente paso:");

        navigateButton.setText("Avanzar");
        navigateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                navigateButtonActionPerformed(evt);
            }
        });

        logTextArea.setColumns(20);
        logTextArea.setRows(5);
        jScrollPane1.setViewportView(logTextArea);

        jLabel9.setText("Nodos visitados:");

        javax.swing.GroupLayout navigatePanelLayout = new javax.swing.GroupLayout(navigatePanel);
        navigatePanel.setLayout(navigatePanelLayout);
        navigatePanelLayout.setHorizontalGroup(
            navigatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navigatePanelLayout.createSequentialGroup()
                .addGroup(navigatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, navigatePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE))
                    .addGroup(navigatePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(navigatePanelLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(navigatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(destComboBox3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                            .addComponent(ubicationLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(navigateButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        navigatePanelLayout.setVerticalGroup(
            navigatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navigatePanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ubicationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(destComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(navigateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mapPanel.setBackground(new java.awt.Color(255, 255, 255));
        mapPanel.setForeground(new java.awt.Color(255, 255, 255));
        mapPanel.setAlignmentX(1.0F);
        mapPanel.setAlignmentY(1.0F);
        mapPanel.setAutoscrolls(true);
        mapPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));

        toGraphLabel.setBackground(java.awt.Color.white);
        toGraphLabel.setForeground(new java.awt.Color(255, 255, 255));
        mapPanel.setViewportView(toGraphLabel);

        routeMapLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        routeMapLabel.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        routePanel.setViewportView(routeMapLabel);

        fileJMenu.setText("File");

        addLocation.setText("Agregar ubicacion");
        addLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addLocationActionPerformed(evt);
            }
        });
        fileJMenu.add(addLocation);

        addTrafficInfo.setText("Informar trafico");
        addTrafficInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTrafficInfoActionPerformed(evt);
            }
        });
        fileJMenu.add(addTrafficInfo);
        fileJMenu.add(jSeparator1);

        saveMap.setText("Guardar mapa");
        fileJMenu.add(saveMap);

        jMenuBar1.add(fileJMenu);

        jMenu2.setText("Edit");

        graphTreeOption.setText("Graficar arbol B");
        graphTreeOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                graphTreeOptionActionPerformed(evt);
            }
        });
        jMenu2.add(graphTreeOption);
        jMenu2.add(jSeparator5);

        pauseClock.setText("Pausar Reloj");
        pauseClock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pauseClockActionPerformed(evt);
            }
        });
        jMenu2.add(pauseClock);

        editHour.setText("Editar Hora");
        editHour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editHourActionPerformed(evt);
            }
        });
        jMenu2.add(editHour);

        resetClock.setText("Restablecer Reloj");
        resetClock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetClockActionPerformed(evt);
            }
        });
        jMenu2.add(resetClock);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("about Travel Map");

        jMenuItem2.setText("Este proyecto");
        jMenu3.add(jMenuItem2);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(infoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(routeInfoPanel)
                    .addComponent(pathsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(routePanel)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(mapPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(navigatePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(infoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pathsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(routeInfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mapPanel)
                            .addComponent(navigatePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(routePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void travelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_travelButtonActionPerformed

        if (!haveInfo()) {
            return;
        }

        this.orderedBy = orderComboBox.getSelectedIndex();
        NodeG srcNode = adyMatrix.getNodesList().get(srcComboBox1.getSelectedIndex() - 1);
        NodeG destNode = adyMatrix.getNodesList().get(destComboBox2.getSelectedIndex() - 1);
        this.actualPaths = guiController.sortPaths(adyMatrix.travel(srcNode, destNode), orderedBy);
        guiController.setPathsButtons(pathsScroll, this.actualPaths,
                srcNode.getAlias(), destNode.getAlias(), routePanel, routeMapLabel, infoRouteLabel, orderedBy);
        ubicationLabel.setText(srcNode.getAlias());
        guiController.setPrincipalTarget(destNode);
        if (isWalkButton.isSelected()) {
            System.out.println("modo viaje a pata ");

            /*
                TODO metodos usando la matriz de forma no dirigida
                TODO tipo de desgaste caminando
                TODO tiempo a pie
            */

        } else {
            System.out.println("modo runrun ");

            /*
                TODO metodos actuales, grafo dirigido
                TODO consumo de gasolina
                TODO tiempo en carro -> usar formula que implica trafico
            */


        }
        navigatePanel.setVisible(true);

    }//GEN-LAST:event_travelButtonActionPerformed

    private void fullMapViewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fullMapViewButtonActionPerformed

        if (guiController.setImageAsPanel(mapPanel, toGraphLabel, "Graphs/full_map.png")) {
            fullMapViewButton.setText("Ver mapa");
        } else {
            fullMapViewButton.setText("Ocultar");
        }

    }//GEN-LAST:event_fullMapViewButtonActionPerformed

    private void orderByButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderByButtonActionPerformed
        travelButtonActionPerformed(evt);
        infoRouteLabel.setText("");
        infoRouteLabel.repaint();
    }//GEN-LAST:event_orderByButtonActionPerformed

    private void graphTreeOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_graphTreeOptionActionPerformed
        // TODO graficar arbol con graphviz
    }//GEN-LAST:event_graphTreeOptionActionPerformed

    private void navigateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_navigateButtonActionPerformed

        if (!haveInfo()) {
            return;
        }

        NodeG auxPreviousNode = adyMatrix.getNodesList().get(ubicationLabel.getText());
        NodeG targetNode = adyMatrix.getNodesList().get(destComboBox3.getSelectedIndex() - 1);
        guiController.getPathSelected();
        MatrixCell actualCell = adyMatrix.getCell(auxPreviousNode.getId(), targetNode.getId());

        if (actualCell != null && !guiController.getPathSelected().contains(actualCell)) {


            this.actualPaths = guiController.sortPaths(adyMatrix.travel(actualCell.getDestination(), guiController.getPrincipalTarget()), orderedBy);
            guiController.setPathsButtons(pathsScroll, this.actualPaths,
                    actualCell.getDestination().getAlias(), guiController.getPrincipalTarget().getAlias(), routePanel, routeMapLabel, infoRouteLabel, orderedBy);
            JOptionPane.showMessageDialog(null, "Ruta recalculada", "Info", JOptionPane.INFORMATION_MESSAGE);

            if (this.actualPaths.getSize() == 0) {
                System.out.println("No hay caminos");
                this.actualPaths = guiController.sortPaths(adyMatrix.travel(actualCell.getDestination(), auxPreviousNode), orderedBy);
                guiController.setPathsButtons(pathsScroll, this.actualPaths,
                        actualCell.getDestination().getAlias(), guiController.getPrincipalTarget().getAlias(), routePanel, routeMapLabel, infoRouteLabel, orderedBy);
                JOptionPane.showMessageDialog(null, "Ruta recalculada", "Info", JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            System.out.println("No es parte del camino");
        } else {
            guiController.setPreviousCell(actualCell);
            ubicationLabel.setText(targetNode.getAlias());
            destComboBox3.setSelectedIndex(0);
            ubicationLabel.repaint();
            System.out.println("Es parte del camino");
        }


    }//GEN-LAST:event_navigateButtonActionPerformed

    private void isWalkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isWalkButtonActionPerformed
        if (isWalkButton.isSelected()) {
            isWalkButton.setText("Caminando");
        } else {
            isWalkButton.setText("Automovil");
        }
        travelButtonActionPerformed(evt);
    }//GEN-LAST:event_isWalkButtonActionPerformed

    private void pauseClockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pauseClockActionPerformed
       guiController.pauseClock();
    }//GEN-LAST:event_pauseClockActionPerformed

    private void editHourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editHourActionPerformed
        guiController.editClock(this, hourLabel);
    }//GEN-LAST:event_editHourActionPerformed

    private void resetClockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetClockActionPerformed
       guiController.setRealHour();
    }//GEN-LAST:event_resetClockActionPerformed

    private void addLocationActionPerformed(java.awt.event.ActionEvent evt) {

        JFileChooser fileChooser = new JFileChooser();
        int returnValue = fileChooser.showOpenDialog(null);
        if (returnValue == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            this.adyMatrix = new FileManager(adyMatrix).readLocationsFile(selectedFile);
            guiController.setItems(srcComboBox1, adyMatrix.getNodesList());
            guiController.setItems(destComboBox2, adyMatrix.getNodesList());
            guiController.setItems(destComboBox3, adyMatrix.getNodesList());
            fullMapViewButtonActionPerformed(null);

        } else {

        }

    }

    private void addTrafficInfoActionPerformed(java.awt.event.ActionEvent evt) {
        JFileChooser fileChooser = new JFileChooser();
        int returnValue = fileChooser.showOpenDialog(null);
        if (returnValue == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();

            this.adyMatrix = new FileManager(adyMatrix).readTrafficFile(selectedFile, adyMatrix);

        } else {

        }

    }

    private boolean haveInfo() {
        if (adyMatrix.getNodesList() != null) {
            return true;
        } else {
            JOptionPane.showMessageDialog(null, "No hay informacion de ubicaciones", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem addLocation;
    private javax.swing.JMenuItem addTrafficInfo;
    private javax.swing.JComboBox<String> destComboBox2;
    private javax.swing.JComboBox<String> destComboBox3;
    private javax.swing.JMenuItem editHour;
    private javax.swing.JMenu fileJMenu;
    private javax.swing.JButton fullMapViewButton;
    private javax.swing.JMenuItem graphTreeOption;
    private javax.swing.JLabel hourLabel;
    private javax.swing.JPanel infoPanel;
    private javax.swing.JTextArea infoRouteLabel;
    private javax.swing.JToggleButton isWalkButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JTextArea logTextArea;
    private javax.swing.JScrollPane mapPanel;
    private javax.swing.JButton navigateButton;
    private javax.swing.JPanel navigatePanel;
    private javax.swing.JButton orderByButton;
    private javax.swing.JComboBox<String> orderComboBox;
    private javax.swing.JPanel pathsPanel;
    private javax.swing.JPanel pathsScroll;
    private javax.swing.JScrollPane pathsScrollPane;
    private javax.swing.JMenuItem pauseClock;
    private javax.swing.JMenuItem resetClock;
    private javax.swing.JScrollPane routeInfoPanel;
    private javax.swing.JLabel routeMapLabel;
    private javax.swing.JScrollPane routePanel;
    private javax.swing.JMenuItem saveMap;
    private javax.swing.JComboBox<String> srcComboBox1;
    private javax.swing.JLabel toGraphLabel;
    private javax.swing.JButton travelButton;
    private javax.swing.JLabel ubicationLabel;
    // End of variables declaration//GEN-END:variables
}
